# Generated by Django 4.0.1 on 2022-03-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('apiId', models.AutoField(primary_key=True, serialize=False)),
                ('urlreq', models.CharField(max_length=500)),
            ],
        ),
    ]
