# Generated by Django 4.0.1 on 2022-03-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=500)),
                ('port', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Api',
        ),
    ]
