# Generated by Django 4.0.1 on 2022-03-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_url_delete_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='port',
            field=models.CharField(max_length=500),
        ),
    ]
